
tasks:
  build-image:
    type: build
    image: 279455466772.dkr.ecr.us-east-1.amazonaws.com/test
    tags: ["${CI_COMMIT_SHA:0:8}", "latest"]
    push: true
  
  deploy:
    image: checktheflow/elasticbeanstalk-cli
    commands:
      ## install git
      - apk add --no-cache git
      ## set required parameters for eb deploy
      - eb init --platform dockerr --region $EBS_REGION $EBS_APPLICATION
      ## update ebs environment 
      - eb deploy $EBS_ENVIRONMENT 
    environment:
      EBS_APPLICATION: demo
      EBS_REGION: us-east-1
      EBS_ENVIRONMENT: docker
